# Generated by Django 5.0.6 on 2024-06-14 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teacher_panel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("INFORMATION", "Information"),
                            ("BIOMETRIC", "Biometric"),
                        ],
                        default="INFORMATION",
                        max_length=20,
                    ),
                ),
                ("change_date", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decision", models.BooleanField(default=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("CREATE", "Create"),
                            ("DELETE", "Delete"),
                            ("IMPORT", "Import"),
                            ("ADD_PARENT", "Add Parent"),
                            ("HISTORY", "History"),
                            ("ADD_PERMISSION", "Add Permission"),
                            ("SIGN", "Sign"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("INFO", "Info"),
                        ],
                        default="LOGIN",
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="UserConsents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signing_date", models.DateTimeField(auto_now_add=True)),
                ("seen_changes", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name="consents",
            constraint=models.UniqueConstraint(
                fields=("consent_type", "description"),
                name="unique_consent_type_description",
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teacher_panel.children"
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userconsents",
            name="consent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backbone.consents"
            ),
        ),
        migrations.AddField(
            model_name="userconsents",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="userconsents",
            constraint=models.UniqueConstraint(
                fields=("user", "consent"), name="unique_user_consent"
            ),
        ),
    ]
