# Generated by Django 5.0.6 on 2024-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[("ERROR", "Error"), ("NORMAL", "Normal")],
                        default="NORMAL",
                        max_length=6,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("data", models.JSONField()),
            ],
        ),
    ]
